### ISSUE TITLE
Question consultation

### ISSUE THREAD

**Issue by wyzh0912** [Haichao-Zhang/PEX#1]
I am a college student. I'm extremely interested in this paper and I plan to make further research about it.  So I want to ask when I can see the code. I would appreciate it if you could do so. Thanks.

**Comment by Facebear-ljx** [comment]
Dear Haichao,

Thanks for your wonderful work on Offline2Online RL! Your PEX makes a great contribution to the RL commitee and inspires me a lot! I'm a PhD student at Tsinghua university and plan to compare your PEX as a baseline in my up-comming work. So, like wyzh0912, I also want to ask when I can see the code.

Best,
Jianxiong

**Comment by Haichao-Zhang** [comment]
Hi, thanks for your interests in my work. Sorry for the delay and I will try my best to release the code in the next few weeks.

**Comment by wyzh0912** [comment]
Thank you Mr.Zhang.  I am looking forward to that day!

**Comment by Facebear-ljx** [comment]
> 
Thanks！

**Comment by Haichao-Zhang** [comment]
Closed via 0cd4b0444269daebea983d66cdd34f46a55a6fb6.
